# Generated by Django 5.1.6 on 2025-02-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='registration_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='batch',
            field=models.CharField(max_length=255),
        ),
    ]
